<error>
  <time>14:53:53</time>
  <job>ECLIPSE100</job>
  <reason>Process exited with status code 1</reason>
  <stderr>
Traceback (most recent call last):
  File "/prog/res/komodo/2021.08.03-py36-rhel7/root/share/ert/forward-models/res/script/ecl100", line 6, in <module>
    run(config, [arg for arg in sys.argv[1:] if len(arg) > 0])
  File "/prog/res/komodo/2021.08.03-py36-rhel7/root/lib64/python3.6/site-packages/res/fm/ecl/script.py", line 29, in run
    run.runEclipse(eclrun_config=eclrun_config)
  File "/prog/res/komodo/2021.08.03-py36-rhel7/root/lib64/python3.6/site-packages/res/fm/ecl/ecl_run.py", line 323, in runEclipse
    self.assertECLEND()
  File "/prog/res/komodo/2021.08.03-py36-rhel7/root/lib64/python3.6/site-packages/res/fm/ecl/ecl_run.py", line 368, in assertECLEND
    % (result.errors, error_msg)
Exception: Eclipse simulation failed with:1 errors:

 @--  ERROR  AT TIME     2404.8   DAYS    ( 1-AUG-2024):
 @                                                                           
 @           RUN STOPPED BECAUSE NUMBER OF PROBLEMS                          
 @           EXCEEDS MAXIMUM PERMITTED VALUE (  7000).                       
</stderr>
  <stderr_file>/scratch/fmu/webviz/webviz-subsurface-testdata/01_drogon_ahm/realization-65/pred_ref/ECLIPSE100.stderr.3</stderr_file>
</error>
